# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Template
version:      2.9
version_from: Template.pm
installdirs:  site
requires:
    Carp:                          0
    Digest::MD5:                   0
    File::Spec:                    0.82
    Scalar::Util:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
